### PR TITLE
A peek at JavaFX (not yet for merging!)

### PR DESCRIPTION
**Pull request by iKarith**
This is offered not for merging, but for commentary.  :)  This is the bare beginnings of a JavaFX port of the GUI. 

The main window works like the one from SWT—Swing had some idea of trying to have a tabbed interface for the open disks, and I think that didn't work out.  Willing to revisit that if it seems to make sense in the future.  I've implemented the Swing menubar and, if you check out iKarith/AppleCommander's javafx branch, you'll see it sits on the menubar on the Mac.  We could make this a proper menubar, if we choose to.  In fact, we could even conditionally leave the exit item off the File menu and add a Window menu on the Mac if we wanted to.

Only the Open and About buttons are connected to anything.

The DiskWindow just has Files tab containing a ToolBar (with a placeholder button) and a SplitPane with a TreeView on the left and nothing interesting on the right yet.  The TreeView expands the first disk in the file you open IFF there is only one.  There's a dummy TreeItem root you don't see there (because I've hidden it) so there can be more than one disk in a file.  The only such file I've got easy to hand is UniDOS and AppleCommander can't read UniDOS's modified two-volume-per-disk RWTS.

JavaFX expects toString() methods on objects associated with UI elements to provide text labels for them, and I decided not to fight this since the items in question had no specific toString() methods.  There's an alternative to this if you'd rather not do that since toString() might otherwise be useful for debugging if it outputs class and random hex string (pointer probably?)  I've been using it that way.  :)  You'd instead create something that looks at the TreeItem and figures out hot to label it by determining its instance type.  It's more complicated, so I opted for implementing toString().

That's about it so far, I've spent a lot of time learning how SWT and JavaFX do things differently, so it's gone slow.

### CODE REVIEW

**Comment by iKarith** [comment]
Some things I have rattling around in my head (since github doesn't really give us anything like slack to talk about these things, I figured this is a good place):

- Redoing the UI images as SVG, even just as masters.  I've got the Compare Image Wizard as a template.  I don't know the fonts used for the text in the other splash logos so I can't recreate them exactly without a little help.  :)  I considered doing them in GIMP, but resolution independence is a thing, and a large part of the reason to bother.

- Although JavaFX displays SVG fine in a WebView, its programmatic API doesn't yet.  Unless we want to just start implementing all of our graphical elements in WebViews (not as crazy an idea as it used to be I admit), we'd need something like codecentric/javafxsvg to display them in places we'd use JavaFX ImageViews.

- The current three-tab disk explorer … I wonder if that information doesn't fit into one tab pretty easily on a large screen.  Probably not a low-res one though because 256x256 for a disk map is a pretty big chunk of a low-res screen.  Responsive UI design maybe?  I'll have to investigate whether this is possible.

Most of these things don't have to be done now—and should not be given higher priorities—but there's some planning I guess I could be doing for the last one.  That's assuming there aren't major suggestions for how I should change what I'm doing to implement the UI in the first place.

**Comment by a2geek** [comment]
I definitely like the concept! And don't worry about time.  This has been around for 15 years, and the UI is what I thought would be needed, but the `ac` tools is by far the most used component!  

Both the SWT GUI and Swing GUI (what little there is) were done by me and I am by no means a UI person - I usually am back-end type activity.  So rearrange and please do make it better.

Also feel free to tinker with the images as you'd like. I think my only caveat is try to do better at picking tooling that will (a) stick around and (b) be free/open source so others can riff off of it.  I used Microsoft PhotoDraw 2 (the `*.mix` files) as I recall and can't find anything to convert them, so the `imageSource` is utterly worthless at this point.

I just pulled your repo and switched to the `javafx` branch.  It does launch but I couldn't open a file - I get ...
```
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Folder parameter must be a valid folder
	at com.sun.glass.ui.CommonDialogs.convertFolder(CommonDialogs.java:238)
	at com.sun.glass.ui.CommonDialogs.showFileChooser(CommonDialogs.java:190)
	at com.sun.javafx.tk.quantum.QuantumToolkit.showFileChooser(QuantumToolkit.java:1496)
	at javafx.stage.FileChooser.showDialog(FileChooser.java:416)
	at javafx.stage.FileChooser.showOpenDialog(FileChooser.java:350)
	at com.webcodepro.applecommander.ui.fx.FXAppleCommander.openFile(FXAppleCommander.java:197)
	at com.webcodepro.applecommander.ui.fx.FXAppleCommander.handleAction(FXAppleCommander.java:101)
	at com.webcodepro.applecommander.ui.fx.FXAppleCommander.lambda$createMenuBar$4(FXAppleCommander.java:148)
```
... so not certain what's up there?  I'll try to poke around, maybe I have a bum path in a preferences file somewhere.

When I've played with JavaFX, I was tinkering with [SceneBuilder](http://gluonhq.com/products/scene-builder/) just in case that helps and you're not aware of the tool.

Agreed, a forum would be nice!

**Comment by a2geek** [comment]
LOL, it's because I never used the FX AppleCommander before!  Just need to handle `null` differently.  Something like this in `openFile(...)`:
```java
String pathName = userPreferences.getDiskImageDirectory();
if (null != pathName) {
    fileChooser.setInitialDirectory(new File(pathName));
}
```

**Comment by iKarith** [comment]
Oh, thanks, yes, an un-handled null should be handled!  :)  Oops.

At the moment the only thing I have outstanding is my effort to see if I can coax a DialogPane into inheriting the Modena CSS for an Alert.  I sort of realized that one of the things about Swing and AWT I never really liked was how messy the code was to describe the UI itself.  Oracle no longer bothers to give you a nice download fo SceeBuilder, but Gluon does, and FXML would sure make experimenting with alternate UIs and developing responsive UIs a lot easier.

I've got to step away from it for about a week or so to focus on some RL responsibilities, but if he's free that may be a perfect time for Brendan Robert (@badvision to poke at it.  He's the one who recommended JavaFX and offered to help with the porting.  I've had to re-learn some Swing (and Java for that matter, so I know I'm not yet writing GOOD Java) and learn some SWT and JavaFX at the same time.  Theoretically he knows what he's doing and doesn't need to bumble through it like I do.  No idea if he'd do it as FXML or as code yet, but I figure it'll be easier to tweak things optimally once the port works in the first place.  And the sooner it works at all, the sooner we can wave goodbye to SWT.

As you said, this has been kind if been what it's been for a decade and a half now.  I dunno if you'd even have used Java two write it today given lots of compiled and interpreted alternatives that you could choose, but I'd certainly love to see AppleCommander reach a state where Mac and Linux users won't wish they had CiderPress.  :)

**Comment by a2geek** [comment]
Did you want to leave this open yet or is it ok for me to close it out?  I presume that should it make more progress you can just open a new PR.

**Comment by a2geek** [comment]
Just cleaning up a bit. Submit a new PR if you have more to show off!

**Pull request closed without merging**
